### ISSUE TITLE
https://enlight.ml is gone!

### ISSUE THREAD

**Issue by shamdasani** [TryEnlight/tryenlight.github.io#15]
My free domain name provider, Freenom, took away https://enlight.ml....
This is completely on me, and I am looking for a new name, possibly a re-brand. Any suggestions?

**Comment by shamdasani** [comment]
It should be accessible at https://tryenlight.github.io for now

**Comment by Cristilupchian** [comment]
not accessible :)

**Comment by yhdesai** [comment]
It probably should be just https://tryenlight.github.io/

**Comment by shamdasani** [comment]
oh yes @Cristilupchian it’s https://tryenlight.github.io
