### ISSUE TITLE
Enlight domain suggestions

### ISSUE THREAD

**Issue by shamdasani** [TryEnlight/tryenlight.github.io#24]
Hello Enlighters!

I am looking for a new domain for Enlight. Leave your suggestions below! I was thinking something like tryenlight.com or enlight.build, but I'm not 100% set on one of those. 

Also, feel free to comment future project ideas as well. Expect to see some sweet content coming soon!

**Comment by ifvictr** [comment]
enlight.sh and enlight.codes :)

**Comment by Ornataweaver** [comment]
enlight.idea
enlight.ideas
enlight.io
enlight.bit
enlight on ZeroNet
