### ISSUE TITLE
Documents for contribution

### ISSUE THREAD

**Issue by TheYahya** [TryEnlight/tryenlight.github.io#26]
For making it easy to contribute and run the project locally, It's need to be clean up, and a little documented, the way the site build & generate with `jekyll` is a blind spot for any new user that take a look at it.

**Comment by shamdasani** [comment]
Just made a few changes. If you think more needs to be added, feel free to send a pull request!

**Comment by TheYahya** [comment]
Thanks! I will do it. :relaxed:
