### ISSUE TITLE
missing images on https://enlight.ml/projects/text-editor/text-editor.html

### ISSUE THREAD

**Issue by pleabargain** [TryEnlight/tryenlight.github.io#6]
https://enlight.ml/projects/text-editor/text-editor.html
The page doesn't look right... missing content.

**Comment by shamdasani** [comment]
@pleabargain can you send a screen shot? Looks fine for me...

**Comment by complxalgorithm** [comment]
@samayshamdasani I second that; nothing was wrong when I visited that page.
